ALTER TABLE CLASE DROP FOREIGN KEY FK_CLASE_GRUPOS_ID
ALTER TABLE CLASE DROP FOREIGN KEY FK_CLASE_ASIGNATURA_REFERENCIA
ALTER TABLE ASIGNATURAS DROP FOREIGN KEY FK_ASIGNATURAS_TITULACION_CODIGO
ALTER TABLE OPTATIVA DROP FOREIGN KEY FK_OPTATIVA_REFERENCIA
ALTER TABLE ENCUESTA DROP FOREIGN KEY FK_ENCUESTA_EXPEDIENTE_NUM_EXPEDIENTE
ALTER TABLE EXPEDIENTES DROP FOREIGN KEY FK_EXPEDIENTES_TITULACION_CODIGO
ALTER TABLE EXPEDIENTES DROP FOREIGN KEY FK_EXPEDIENTES_ALUMNO_ID
ALTER TABLE MATRICULA DROP FOREIGN KEY FK_MATRICULA_EXPEDIENTES_NUM_EXPEDIENTE
ALTER TABLE GRUPO DROP FOREIGN KEY FK_GRUPO_grupoID
ALTER TABLE GRUPO DROP FOREIGN KEY FK_GRUPO_TITULACION_CODIGO
ALTER TABLE GRUPOS_POR_ASIGNATURA DROP FOREIGN KEY FK_GRUPOS_POR_ASIGNATURA_REFERENCIA_REFERENCIA
ALTER TABLE GRUPOS_POR_ASIGNATURA DROP FOREIGN KEY FK_GRUPOS_POR_ASIGNATURA_ID_ID
ALTER TABLE ASIGNATURAS_MATRICULA DROP FOREIGN KEY FK_ASIGNATURAS_MATRICULA_ASIGNATURA_REFERENCIA
ALTER TABLE ASIGNATURAS_MATRICULA DROP FOREIGN KEY FK_ASIGNATURAS_MATRICULA_CURSO_ACADEMICO
ALTER TABLE ASIGNATURAS_MATRICULA DROP FOREIGN KEY FK_ASIGNATURAS_MATRICULA_GRUPO_ID
ALTER TABLE jn_tit_cntr DROP FOREIGN KEY FK_jn_tit_cntr_centro_fk
ALTER TABLE jn_tit_cntr DROP FOREIGN KEY FK_jn_tit_cntr_tit_fk
ALTER TABLE jn_tit_opt DROP FOREIGN KEY FK_jn_tit_opt_titulaciones_CODIGO
ALTER TABLE jn_tit_opt DROP FOREIGN KEY FK_jn_tit_opt_optativa_REFERENCIA
ALTER TABLE jn_enc_grpXasi DROP FOREIGN KEY FK_jn_enc_grpXasi_FECHA_DE_ENVIO
ALTER TABLE jn_enc_grpXasi DROP FOREIGN KEY FK_jn_enc_grpXasi_CURSO_ACADEMICO
ALTER TABLE MATRICULA_ASIGNATURAS DROP FOREIGN KEY MATRICULAASIGNATURASListado_Asignaturas_REFERENCIA
ALTER TABLE MATRICULA_ASIGNATURAS DROP FOREIGN KEY FK_MATRICULA_ASIGNATURAS_CURSO_ACADEMICO
DROP TABLE TITULACION
DROP TABLE ALUMNO
DROP TABLE CLASE
DROP TABLE ASIGNATURAS
DROP TABLE OPTATIVA
DROP TABLE CENTRO
DROP TABLE ENCUESTA
DROP TABLE EXPEDIENTES
DROP TABLE MATRICULA
DROP TABLE GRUPO
DROP TABLE GRUPOS_POR_ASIGNATURA
DROP TABLE ASIGNATURAS_MATRICULA
DROP TABLE jn_tit_cntr
DROP TABLE jn_tit_opt
DROP TABLE jn_enc_grpXasi
DROP TABLE MATRICULA_ASIGNATURAS
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
