package es.uma.informatica.sii.proyecto.test;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
// Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

import es.uma.informatica.sii.anotaciones.Requisitos;
public class DefaultSuiteTestProyectoIT {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    BaseDeDatos.inicializar("SecretariaTest");
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Requisitos({"RF02"})
  @Test
  public void pruebaLogin2() {
    driver.get("http://localhost:8080/proyecto-war/");
    driver.manage().window().setSize(new Dimension(1156, 474));
    driver.findElement(By.cssSelector("h1")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Bienvenido al sistema gestor de alumnado"));
    driver.findElement(By.linkText("Iniciar Sesion")).click();
    driver.findElement(By.id("j_idt6:user")).click();
    driver.findElement(By.id("j_idt6:user")).sendKeys("Secretaria");
    driver.findElement(By.id("j_idt6:pass")).sendKeys("secretaria");
    driver.findElement(By.cssSelector("h1")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Inicia Sesion"));
    driver.findElement(By.name("j_idt6:j_idt15")).click();
    driver.findElement(By.cssSelector("h1")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Seleccione un boton para consultar los datos"));
  }
  @Requisitos({"RF01"})
  @Test
  public void pruebaRegistroUsuario() {
    driver.get("http://localhost:8080/proyecto-war/");
    driver.manage().window().setSize(new Dimension(1156, 474));
    driver.findElement(By.cssSelector("h1")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Bienvenido al sistema gestor de alumnado"));
    driver.findElement(By.linkText("No tengo cuenta")).click();
    driver.findElement(By.id("registro:nombre")).click();
    driver.findElement(By.id("registro:nombre")).sendKeys("Guillermo");
    driver.findElement(By.id("registro:apellidos")).sendKeys("Jimenez");
    driver.findElement(By.id("registro:email")).sendKeys("guijimenez@uma.es");
    driver.findElement(By.id("registro:direccion")).sendKeys("calle prueba");
    driver.findElement(By.id("registro:dni")).sendKeys("12333444x");
    driver.findElement(By.id("registro:telefono")).sendKeys("666777888");
    driver.findElement(By.id("registro:user")).sendKeys("guilleJJ");
    driver.findElement(By.id("registro:pass")).sendKeys("pass");
    driver.findElement(By.id("registro:repass")).sendKeys("pass");
    driver.findElement(By.name("registro:j_idt24")).click();
    assertThat(driver.findElement(By.cssSelector("p:nth-child(1)")).getText(), is("El registro se ha realizado con exito. Hemos enviado un mensaje de validacion a su correo electronico. Compruebelo y pulse el enlace para validar la cuenta de usuario."));
  }
  @Requisitos({"RF02"})
  @Test
  public void pruebaLoginAlumno() {
    driver.get("http://localhost:8080/proyecto-war/");
    driver.manage().window().setSize(new Dimension(1160, 532));
    driver.findElement(By.linkText("Iniciar Sesion")).click();
    driver.findElement(By.id("j_idt6:user")).click();
    driver.findElement(By.id("j_idt6:user")).sendKeys("Pepe");
    driver.findElement(By.id("j_idt6:pass")).sendKeys("pepaso");
    driver.findElement(By.cssSelector("h1")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Inicia Sesion"));
    driver.findElement(By.name("j_idt6:j_idt15")).click();
    driver.findElement(By.cssSelector("h1")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Encuesta"));
  }
  @Requisitos({"RF07"})
  @Test
  public void pruebaLeerUsuario() {
    driver.get("http://localhost:8080/proyecto-war/");
    driver.manage().window().setSize(new Dimension(1160, 532));
    driver.findElement(By.linkText("Iniciar Sesion")).click();
    driver.findElement(By.id("j_idt6:user")).click();
    driver.findElement(By.id("j_idt6:user")).sendKeys("Secretaria");
    driver.findElement(By.id("j_idt6:pass")).sendKeys("secretaria");
    driver.findElement(By.cssSelector("h1")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Inicia Sesion"));
    driver.findElement(By.name("j_idt6:j_idt15")).click();
    driver.findElement(By.linkText("Gestor de usuarios")).click();
    driver.findElement(By.cssSelector("h1")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Gestor de usuarios"));
    driver.findElement(By.linkText("Leer informacion de un usuario")).click();
    driver.findElement(By.cssSelector("h1")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Gestor de usuarios"));
    driver.findElement(By.name("j_idt6:j_idt8")).click();
    driver.findElement(By.name("j_idt6:j_idt8")).sendKeys("guilleJJ");
    driver.findElement(By.name("j_idt6:j_idt10")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(2)")).getText(), is("Usuario ==> Nombre: Guillermo, Apellido: Jimenez, DNI: 12333444x, Email: guijimenez@uma.es, Telefono: 666777888, Direccion: calle prueba"));
  }
  @Requisitos({"RF07"})
  @Test
  public void pruebaActualizarUsuario() {
    driver.get("http://localhost:8080/proyecto-war/");
    driver.manage().window().setSize(new Dimension(1160, 532));
    driver.findElement(By.linkText("Iniciar Sesion")).click();
    driver.findElement(By.cssSelector("h1")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Inicia Sesion"));
    driver.findElement(By.id("j_idt6:user")).click();
    driver.findElement(By.id("j_idt6:user")).sendKeys("Secretaria");
    driver.findElement(By.id("j_idt6:pass")).sendKeys("secretaria");
    driver.findElement(By.name("j_idt6:j_idt15")).click();
    driver.findElement(By.id("content")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Seleccione un boton para consultar los datos"));
    driver.findElement(By.linkText("Gestor de usuarios")).click();
    driver.findElement(By.cssSelector("h1")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Gestor de usuarios"));
    driver.findElement(By.linkText("Actualizar informacion de un usuario")).click();
    driver.findElement(By.cssSelector("h1")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Gestor de usuarios"));
    driver.findElement(By.name("j_idt6:j_idt8")).click();
    driver.findElement(By.name("j_idt6:j_idt8")).sendKeys("Pepe");
    driver.findElement(By.name("j_idt6:j_idt10")).click();
    driver.findElement(By.name("j_idt6:j_idt10")).sendKeys("nuevo@uma.es");
    driver.findElement(By.name("j_idt6:j_idt12")).click();
    driver.findElement(By.name("j_idt6:j_idt12")).sendKeys("888999777");
    driver.findElement(By.name("j_idt6:j_idt14")).click();
    driver.findElement(By.name("j_idt6:j_idt14")).sendKeys("nueva direccion");
    driver.findElement(By.name("j_idt6:j_idt16")).click();
    driver.findElement(By.linkText("Volver")).click();
    driver.findElement(By.linkText("Leer informacion de un usuario")).click();
    driver.findElement(By.name("j_idt6:j_idt8")).click();
    driver.findElement(By.name("j_idt6:j_idt8")).sendKeys("Pepe");
    driver.findElement(By.name("j_idt6:j_idt10")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(2)")).getText(), is("Usuario ==> Nombre: PepeLu, Apellido: Pepon, DNI: 12345678x, Email: nuevo@uma.es, Telefono: 888999777, Direccion: nueva direccion"));
  }
  @Requisitos({"RF07"})
  @Test
  public void pruebaBorrarUsuario() {
    driver.get("http://localhost:8080/proyecto-war/");
    driver.manage().window().setSize(new Dimension(1160, 532));
    driver.findElement(By.linkText("Iniciar Sesion")).click();
    driver.findElement(By.id("j_idt6:user")).click();
    driver.findElement(By.id("j_idt6:user")).sendKeys("Secretaria");
    driver.findElement(By.id("j_idt6:pass")).click();
    driver.findElement(By.id("j_idt6:pass")).sendKeys("secretaria");
    driver.findElement(By.name("j_idt6:j_idt15")).click();
    driver.findElement(By.id("content")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Seleccione un boton para consultar los datos"));
    driver.findElement(By.linkText("Gestor de usuarios")).click();
    driver.findElement(By.cssSelector("h1")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Gestor de usuarios"));
    driver.findElement(By.linkText("Borrar un usuario")).click();
    driver.findElement(By.cssSelector("h1")).click();
    driver.findElement(By.cssSelector("th")).click();
    assertThat(driver.findElement(By.cssSelector("th")).getText(), is("Usuario a borrar:"));
    driver.findElement(By.name("j_idt6:j_idt8")).click();
    driver.findElement(By.name("j_idt6:j_idt8")).sendKeys("guilleJJ");
    driver.findElement(By.name("j_idt6:j_idt10")).click();
    driver.findElement(By.linkText("Gestor de usuarios")).click();
    driver.findElement(By.linkText("Leer informacion de un usuario")).click();
    driver.findElement(By.name("j_idt6:j_idt8")).click();
    driver.findElement(By.name("j_idt6:j_idt8")).sendKeys("guilleJJ");
    driver.findElement(By.name("j_idt6:j_idt10")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(2)")).getText(), is("Usuario ==> Nombre: null, Apellido: null, DNI: null, Email: null, Telefono: null, Direccion: null"));
  }
  @Requisitos({"RF05"})
  @Test
  public void pruebaLeerAsignatura() {
    driver.get("http://localhost:8080/proyecto-war/indexSecretaria.xhtml");
    driver.manage().window().setSize(new Dimension(1054, 808));
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Seleccione un boton para consultar los datos"));
    driver.findElement(By.linkText("Gestor de asignaturas")).click();
    driver.findElement(By.linkText("Consultar asignatura")).click();
    driver.findElement(By.id("j_idt6:referencia")).click();
    driver.findElement(By.id("j_idt6:referencia")).sendKeys("11223344");
    driver.findElement(By.name("j_idt6:j_idt12")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(2)")).getText(), is("Asignaturas con Referencia= 11223344, Codigo= 111, Nombre= Estructura de Datos, Creditos= 6, Ofertada= Si, Curso= null, Caracter= null, Duracion= null, Unidad_Temporal= null, Idiomas_Imparticion= null"));
    driver.findElement(By.linkText("Volver")).click();
  }
  @Requisitos({"RF06"})
  @Test
  public void pruebaLeerTitulacion() {
    driver.get("http://localhost:8080/proyecto-war/");
    driver.manage().window().setSize(new Dimension(1160, 532));
    driver.findElement(By.linkText("Iniciar Sesion")).click();
    driver.findElement(By.id("j_idt6:user")).click();
    driver.findElement(By.id("j_idt6:user")).sendKeys("Secretaria");
    driver.findElement(By.id("j_idt6:pass")).sendKeys("secretaria");
    driver.findElement(By.name("j_idt6:j_idt15")).click();
    driver.findElement(By.id("content")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Seleccione un boton para consultar los datos"));
    driver.findElement(By.linkText("Gestor de titulaciones")).click();
    driver.findElement(By.cssSelector("h1")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Gestor de titulaciones"));
    driver.findElement(By.linkText("Leer informacion de una titulacion")).click();
    driver.findElement(By.cssSelector("th")).click();
    assertThat(driver.findElement(By.cssSelector("th")).getText(), is("Titulacion a leer:"));
    driver.findElement(By.id("j_idt6:codigo")).click();
    driver.findElement(By.id("j_idt6:codigo")).sendKeys("1041");
    driver.findElement(By.name("j_idt6:j_idt11")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(2)")).getText(), is("Titulacion: Codigo=1041, Creditos=240, Nombre=Ingenieria Informatica"));
  }
  @Requisitos({"RF05"})
  @Test
  public void pruebaActualizarAsignatura() {
    driver.get("http://localhost:8080/proyecto-war/indexSecretaria.xhtml");
    driver.manage().window().setSize(new Dimension(1054, 808));
    driver.findElement(By.linkText("Gestor de asignaturas")).click();
    driver.findElement(By.linkText("Modificar asignatura")).click();
    driver.findElement(By.id("asignatura:referencia")).click();
    driver.findElement(By.id("asignatura:referencia")).sendKeys("11223344");
    driver.findElement(By.id("asignatura:codigo")).click();
    driver.findElement(By.id("asignatura:codigo")).sendKeys("123");
    driver.findElement(By.id("asignatura:nombre")).click();
    driver.findElement(By.id("asignatura:nombre")).sendKeys("Programacion");
    driver.findElement(By.id("asignatura:creditos")).click();
    driver.findElement(By.id("asignatura:creditos")).sendKeys("12");
    driver.findElement(By.id("asignatura:ofertada")).click();
    driver.findElement(By.id("asignatura:ofertada")).sendKeys("No");
    driver.findElement(By.id("asignatura:curso")).click();
    driver.findElement(By.id("asignatura:curso")).sendKeys("2");
    driver.findElement(By.id("asignatura:caracter")).click();
    driver.findElement(By.id("asignatura:caracter")).sendKeys("Presencial");
    driver.findElement(By.id("asignatura:duracion")).click();
    driver.findElement(By.id("asignatura:duracion")).sendKeys("Mucho");
    driver.findElement(By.id("asignatura:uTemp")).click();
    driver.findElement(By.id("asignatura:uTemp")).sendKeys("Primer cuatri");
    driver.findElement(By.id("asignatura:idiomas")).click();
    driver.findElement(By.id("asignatura:idiomas")).sendKeys("Ingles");
    driver.findElement(By.name("asignatura:j_idt27")).click();
    driver.findElement(By.linkText("Gestor de asignaturas")).click();
    driver.findElement(By.linkText("Consultar asignatura")).click();
    driver.findElement(By.id("j_idt6:referencia")).click();
    driver.findElement(By.id("j_idt6:referencia")).sendKeys("11223344");
    driver.findElement(By.name("j_idt6:j_idt12")).click();
    driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(2)")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(2)")).getText(), is("Asignaturas con Referencia= 11223344, Codigo= 123, Nombre= Programacion, Creditos= 6, Ofertada= No, Curso= 2, Caracter= Presencial, Duracion= Mucho, Unidad_Temporal= Primer cuatri, Idiomas_Imparticion= Ingles"));
    driver.findElement(By.linkText("Volver")).click();
  }
  @Requisitos({"RF06"})
  @Test
  public void pruebaActualizarTitulacion() {
    driver.get("http://localhost:8080/proyecto-war/");
    driver.manage().window().setSize(new Dimension(1160, 532));
    driver.findElement(By.linkText("Iniciar Sesion")).click();
    driver.findElement(By.id("j_idt6:user")).click();
    driver.findElement(By.id("j_idt6:user")).sendKeys("Secretaria");
    driver.findElement(By.id("j_idt6:pass")).sendKeys("secretaria");
    driver.findElement(By.id("j_idt6:pass")).sendKeys(Keys.ENTER);
    driver.findElement(By.linkText("Gestor de titulaciones")).click();
    driver.findElement(By.id("content")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Gestor de titulaciones"));
    driver.findElement(By.linkText("Actualizar informacion de una titulacion")).click();
    driver.findElement(By.id("j_idt6:codigo")).click();
    driver.findElement(By.id("j_idt6:codigo")).sendKeys("1042");
    driver.findElement(By.id("j_idt6:nombre")).click();
    driver.findElement(By.id("j_idt6:nombre")).sendKeys("Ingenieria de Computadores");
    driver.findElement(By.id("j_idt6:creditos")).click();
    driver.findElement(By.id("j_idt6:creditos")).sendKeys("250");
    driver.findElement(By.name("j_idt6:j_idt20")).click();
    driver.findElement(By.linkText("Gestor de titulaciones")).click();
    driver.findElement(By.linkText("Leer informacion de una titulacion")).click();
    driver.findElement(By.id("j_idt6:codigo")).click();
    driver.findElement(By.id("j_idt6:codigo")).sendKeys("1042");
    driver.findElement(By.name("j_idt6:j_idt11")).click();
    driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(2)")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(2)")).getText(), is("Titulacion: Codigo=1042, Creditos=250, Nombre=Ingenieria de Computadores"));
  }
  @Requisitos({"RF06"})
  @Test
  public void pruebaBorrarTitulacion() {
    driver.get("http://localhost:8080/proyecto-war/");
    driver.manage().window().setSize(new Dimension(1160, 532));
    driver.findElement(By.linkText("Iniciar Sesion")).click();
    driver.findElement(By.id("j_idt6:user")).click();
    driver.findElement(By.id("j_idt6:user")).sendKeys("Secretaria");
    driver.findElement(By.id("j_idt6:pass")).sendKeys("secretaria");
    driver.findElement(By.name("j_idt6:j_idt15")).click();
    driver.findElement(By.linkText("Gestor de titulaciones")).click();
    driver.findElement(By.linkText("Borrar una titulacion")).click();
    driver.findElement(By.id("j_idt6:codigo")).click();
    driver.findElement(By.id("j_idt6:codigo")).sendKeys("1042");
    driver.findElement(By.name("j_idt6:j_idt12")).click();
    driver.findElement(By.linkText("Gestor de titulaciones")).click();
    driver.findElement(By.linkText("Leer informacion de una titulacion")).click();
    driver.findElement(By.id("j_idt6:codigo")).click();
    driver.findElement(By.id("j_idt6:codigo")).sendKeys("1042");
    driver.findElement(By.name("j_idt6:j_idt11")).click();
    driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(2)")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(2)")).getText(), is("Titulacion: Codigo=1042, Creditos=null, Nombre=null"));
  }
  @Requisitos({"RF08"})
  @Test
  public void pruebaLeerNotaMedia() {
    driver.get("http://localhost:8080/proyecto-war/");
    driver.manage().window().setSize(new Dimension(1536, 872));
    driver.get("http://localhost:8080/proyecto-war/indexSecretaria.xhtml");
    driver.findElement(By.linkText("Gestor de expedientes")).click();
    driver.findElement(By.linkText("Consultar nota media")).click();
    driver.findElement(By.id("j_idt6:Num_Expediente")).click();
    driver.findElement(By.id("j_idt6:Num_Expediente")).sendKeys("123456789");
    driver.findElement(By.name("j_idt6:j_idt12")).click();
    driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(2)")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(2)")).getText(), is("La nota media es 7.0"));
    driver.findElement(By.linkText("Volver")).click();
  }
  @Requisitos({"RF08"})
  @Test
  public void pruebaActualizarNotaMedia() {
    driver.get("http://localhost:8080/proyecto-war/");
    driver.manage().window().setSize(new Dimension(1536, 872));
    driver.get("http://localhost:8080/proyecto-war/indexSecretaria.xhtml");
    driver.findElement(By.linkText("Gestor de expedientes")).click();
    driver.findElement(By.linkText("Modificar nota media")).click();
    driver.findElement(By.id("j_idt6:Num_Expediente")).click();
    driver.findElement(By.id("j_idt6:Num_Expediente")).sendKeys("123456789");
    driver.findElement(By.cssSelector("tr:nth-child(2) > td")).click();
    driver.findElement(By.id("j_idt6:notaMedia")).click();
    driver.findElement(By.id("j_idt6:notaMedia")).sendKeys("5");
    driver.findElement(By.name("j_idt6:j_idt16")).click();
    driver.findElement(By.linkText("Gestor de expedientes")).click();
    driver.findElement(By.linkText("Consultar nota media")).click();
    driver.findElement(By.id("j_idt6:Num_Expediente")).click();
    driver.findElement(By.id("j_idt6:Num_Expediente")).sendKeys("123456789");
    driver.findElement(By.name("j_idt6:j_idt12")).click();
    driver.findElement(By.id("j_idt6")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(2)")).getText(), is("La nota media es 5.0"));
    driver.findElement(By.linkText("Volver")).click();
  }
  @Requisitos({"RF08"})
  @Test
  public void pruebaBorrarNotaMedia() {
    driver.get("http://localhost:8080/proyecto-war/");
    driver.manage().window().setSize(new Dimension(1536, 872));
    driver.get("http://localhost:8080/proyecto-war/indexSecretaria.xhtml");
    driver.findElement(By.linkText("Gestor de expedientes")).click();
    driver.findElement(By.linkText("Eliminar nota media")).click();
    driver.findElement(By.id("j_idt6:Num_Expediente")).click();
    driver.findElement(By.id("j_idt6:Num_Expediente")).sendKeys("123456789");
    driver.findElement(By.name("j_idt6:j_idt12")).click();
    driver.findElement(By.linkText("Gestor de expedientes")).click();
    driver.findElement(By.linkText("Consultar nota media")).click();
    driver.findElement(By.id("j_idt6:Num_Expediente")).click();
    driver.findElement(By.id("j_idt6:Num_Expediente")).sendKeys("123456789");
    driver.findElement(By.name("j_idt6:j_idt12")).click();
    driver.findElement(By.cssSelector("table")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(2)")).getText(), is("La nota media es 0.0"));
    driver.findElement(By.linkText("Volver")).click();
  }
  @Requisitos({"RF05"})
  @Test
  public void pruebaBorrarAsignatura() {
    driver.get("http://localhost:8080/proyecto-war/indexSecretaria.xhtml");
    driver.manage().window().setSize(new Dimension(1056, 810));
    driver.findElement(By.linkText("Gestor de asignaturas")).click();
    driver.findElement(By.linkText("Eliminar asignatura")).click();
    driver.findElement(By.id("asignatura:referencia")).click();
    driver.findElement(By.id("asignatura:referencia")).sendKeys("11223344");
    driver.findElement(By.name("asignatura:j_idt9")).click();
    driver.findElement(By.linkText("Gestor de asignaturas")).click();
    driver.findElement(By.linkText("Consultar asignatura")).click();
    driver.findElement(By.id("j_idt6:referencia")).click();
    driver.findElement(By.id("j_idt6:referencia")).sendKeys("11223344");
    driver.findElement(By.name("j_idt6:j_idt12")).click();
    driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(2)")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(2)")).getText(), is("Asignaturas con Referencia= 11223344, Codigo= null, Nombre= null, Creditos= null, Ofertada= null, Curso= null, Caracter= null, Duracion= null, Unidad_Temporal= null, Idiomas_Imparticion= null"));
    driver.findElement(By.linkText("Volver")).click();
  }
  @Requisitos({"RF09"})
  @Test
  public void pruebaLeerMatricula() {
    driver.get("http://localhost:8080/proyecto-war/");
    driver.manage().window().setSize(new Dimension(1160, 707));
    driver.findElement(By.linkText("Iniciar Sesion")).click();
    driver.findElement(By.id("j_idt6:user")).click();
    driver.findElement(By.id("j_idt6:user")).sendKeys("Secretaria");
    driver.findElement(By.id("j_idt6:pass")).click();
    driver.findElement(By.id("j_idt6:pass")).sendKeys("secretaria");
    driver.findElement(By.name("j_idt6:j_idt15")).click();
    driver.findElement(By.linkText("Gestor de expedientes")).click();
    driver.findElement(By.cssSelector("h1")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Gestor de expedientes"));
    driver.findElement(By.linkText("Consultar matricula")).click();
    driver.findElement(By.cssSelector("h1")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Gestor de matriculas"));
    driver.findElement(By.id("j_idt6:Num_Expediente")).click();
    driver.findElement(By.id("j_idt6:Num_Expediente")).sendKeys("123456789");
    driver.findElement(By.id("j_idt6:curso")).click();
    driver.findElement(By.id("j_idt6:curso")).sendKeys("20/21");
    driver.findElement(By.name("j_idt6:j_idt16")).click();
    driver.findElement(By.cssSelector("tr:nth-child(4) > td:nth-child(2)")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) > td:nth-child(2)")).getText(), is("Matricula [Curso_academico=20/21, Estado=activo, Num_Archivo=null, Turno_Preferente=null, Fecha_de_matricula=2010-01-10 20:20:20.0, Nuevo_ingreso=null]"));
    driver.findElement(By.linkText("Volver")).click();
  }
  @Requisitos({"RF09"})
  @Test
  public void pruebaBorrarMatricula() {
    driver.get("http://localhost:8080/proyecto-war/");
    driver.manage().window().setSize(new Dimension(1160, 744));
    driver.findElement(By.linkText("Iniciar Sesion")).click();
    driver.findElement(By.id("j_idt6:user")).click();
    driver.findElement(By.id("j_idt6:user")).sendKeys("Secretaria");
    driver.findElement(By.id("j_idt6:pass")).sendKeys("secretaria");
    driver.findElement(By.name("j_idt6:j_idt15")).click();
    driver.findElement(By.linkText("Gestor de expedientes")).click();
    driver.findElement(By.linkText("Eliminar matricula")).click();
    driver.findElement(By.cssSelector("h1")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Gestor de expedientes"));
    driver.findElement(By.id("j_idt6:matricula")).click();
    driver.findElement(By.id("j_idt6:matricula")).sendKeys("987654321");
    driver.findElement(By.id("j_idt6:curso")).click();
    driver.findElement(By.id("j_idt6:curso")).sendKeys("20/21");
    driver.findElement(By.name("j_idt6:j_idt16")).click();
    driver.findElement(By.linkText("Gestor de expedientes")).click();
    driver.findElement(By.linkText("Consultar matricula")).click();
    driver.findElement(By.id("j_idt6:Num_Expediente")).click();
    driver.findElement(By.id("j_idt6:Num_Expediente")).sendKeys("987654321");
    driver.findElement(By.id("j_idt6:curso")).click();
    driver.findElement(By.id("j_idt6:curso")).sendKeys("20/21");
    driver.findElement(By.name("j_idt6:j_idt16")).click();
    driver.findElement(By.cssSelector("tr:nth-child(4) > td:nth-child(2)")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) > td:nth-child(2)")).getText(), is("Matricula [Curso_academico=null, Estado=null, Num_Archivo=null, Turno_Preferente=null, Fecha_de_matricula=null, Nuevo_ingreso=null]"));
  }
  @Requisitos({"RF19"})
  @Test
  public void pruebaBorrarExpediente() {
    driver.get("http://localhost:8080/proyecto-war/");
    driver.manage().window().setSize(new Dimension(1160, 533));
    driver.findElement(By.linkText("Iniciar Sesion")).click();
    driver.findElement(By.id("j_idt6:user")).click();
    driver.findElement(By.id("j_idt6:user")).sendKeys("Secretaria");
    driver.findElement(By.id("j_idt6:pass")).sendKeys("secretaria");
    driver.findElement(By.name("j_idt6:j_idt15")).click();
    driver.findElement(By.linkText("Gestor de expedientes")).click();
    driver.findElement(By.linkText("Eliminar expediente")).click();
    driver.findElement(By.cssSelector("h1")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Gestor de expedientes"));
    driver.findElement(By.id("j_idt6:expediente")).click();
    driver.findElement(By.id("j_idt6:expediente")).sendKeys("987654321");
    driver.findElement(By.name("j_idt6:j_idt12")).click();
  }
  @Requisitos({"RF04"})
  @Test
  public void pruebaActualizarAlumno() {
    driver.get("http://localhost:8080/proyecto-war/");
    driver.manage().window().setSize(new Dimension(968, 714));
    driver.get("http://localhost:8080/proyecto-war/indexSecretaria.xhtml");
    driver.findElement(By.linkText("Gestor de alumnos")).click();
    driver.findElement(By.linkText("Actualizar informacion de un alumno")).click();
    driver.findElement(By.name("j_idt6:j_idt8")).click();
    driver.findElement(By.name("j_idt6:j_idt8")).sendKeys("2");
    driver.findElement(By.name("j_idt6:j_idt10")).click();
    driver.findElement(By.name("j_idt6:j_idt10")).sendKeys("nuevo@uma.es");
    driver.findElement(By.name("j_idt6:j_idt12")).click();
    driver.findElement(By.name("j_idt6:j_idt12")).sendKeys("nuevo@gmail.com");
    driver.findElement(By.name("j_idt6:j_idt14")).click();
    driver.findElement(By.name("j_idt6:j_idt14")).sendKeys("654321123");
    driver.findElement(By.name("j_idt6:j_idt16")).click();
    driver.findElement(By.name("j_idt6:j_idt16")).sendKeys("654321123");
    driver.findElement(By.name("j_idt6:j_idt18")).click();
    driver.findElement(By.name("j_idt6:j_idt18")).sendKeys("calle lola indigo");
    driver.findElement(By.name("j_idt6:j_idt20")).sendKeys("23776");
    driver.findElement(By.name("j_idt6:j_idt22")).sendKeys("Malaga");
    driver.findElement(By.name("j_idt6:j_idt24")).sendKeys("Malaga");
    driver.findElement(By.name("j_idt6:j_idt26")).click();
    driver.findElement(By.linkText("Gestor de alumnos")).click();
    driver.findElement(By.linkText("Leer informacion de un alumno")).click();
    driver.findElement(By.name("j_idt6:j_idt8")).click();
    driver.findElement(By.name("j_idt6:j_idt8")).sendKeys("2");
    driver.findElement(By.name("j_idt6:j_idt10")).click();
    driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(2)")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(2)")).getText(), is("Alumno 2 con DNI=87654321a, Nombre=Luisa, Apellido1=Lopez, Apellido2=null, Email_institucional=nuevo@uma.es, Email_personal=nuevo@gmail.com, Telefono=654321123, Movil=654321123, Direccion=calle lola indigo, Codigo_postal=23776, Localidad=Malaga, Provincia=Malaga"));
    driver.findElement(By.linkText("Volver")).click();
  }
    @Requisitos({"RF11"})
  @Test
  public void pruebaActualizarEncuesta() {
    driver.get("http://localhost:8080/proyecto-war/");
    driver.manage().window().setSize(new Dimension(968, 714));
    driver.get("http://localhost:8080/proyecto-war/indexSecretaria.xhtml");
    driver.findElement(By.linkText("Gestor de encuesta")).click();
    driver.findElement(By.linkText("Actualizar una Encuesta")).click();
    driver.findElement(By.id("j_idt6:expediente")).click();
    driver.findElement(By.id("j_idt6:expediente")).sendKeys("123456789");
    driver.findElement(By.id("j_idt6:Fecha")).click();
    driver.findElement(By.id("j_idt6:Fecha")).sendKeys("27-07-2000");
    driver.findElement(By.id("j_idt6:gp1")).click();
    driver.findElement(By.id("j_idt6:gp1")).sendKeys("1A");
    driver.findElement(By.id("j_idt6:gp2")).click();
    driver.findElement(By.id("j_idt6:gp2")).sendKeys("2B");
    driver.findElement(By.id("j_idt6:gp3")).click();
    driver.findElement(By.id("j_idt6:gp3")).sendKeys("3C");
    driver.findElement(By.name("j_idt6:j_idt32")).click();
    driver.findElement(By.linkText("Gestor de encuesta")).click();
    driver.findElement(By.linkText("Leer Encuestas")).click();
    driver.findElement(By.id("j_idt6:expediente")).sendKeys("123456789");
    driver.findElement(By.id("j_idt6:Fecha")).sendKeys("27-07-2000");
    driver.findElement(By.name("j_idt6:j_idt16")).click();
    driver.findElement(By.cssSelector("tr:nth-child(4) > td:nth-child(2)")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) > td:nth-child(2)")).getText(), is("Encuesta fecha_de_envio=27-07-2000, grupoPrimero=1A, grupoSegundo=2B, grupoTercero=3C, grupoCuarto="));
    driver.findElement(By.linkText("Volver")).click();
    {
      WebElement element = driver.findElement(By.linkText("Volver"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
  }
	@Requisitos({"RF04"})
	 @Test
	  public void pruebaBorrarAlumno() {
	    driver.get("http://localhost:8080/proyecto-war/");
	    driver.manage().window().setSize(new Dimension(1160, 695));
	    driver.findElement(By.linkText("Iniciar Sesion")).click();
	    driver.findElement(By.id("j_idt6:user")).click();
	    driver.findElement(By.id("j_idt6:user")).sendKeys("Secretaria");
	    driver.findElement(By.id("j_idt6:pass")).sendKeys("secretaria");
	    driver.findElement(By.name("j_idt6:j_idt15")).click();
	    driver.findElement(By.linkText("Gestor de alumnos")).click();
	    driver.findElement(By.linkText("Borrar un alumno")).click();
	    driver.findElement(By.name("j_idt6:j_idt8")).click();
	    driver.findElement(By.name("j_idt6:j_idt8")).sendKeys("2");
	    driver.findElement(By.name("j_idt6:j_idt10")).click();
	    driver.findElement(By.linkText("Gestor de alumnos")).click();
	    driver.findElement(By.linkText("Leer informacion de un alumno")).click();
	    driver.findElement(By.name("j_idt6:j_idt8")).click();
	    driver.findElement(By.name("j_idt6:j_idt8")).sendKeys("2");
	    driver.findElement(By.name("j_idt6:j_idt10")).click();
	    driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(2)")).click();
	    assertThat(driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(2)")).getText(), is("Alumno 2 con DNI=null, Nombre=null, Apellido1=null, Apellido2=null, Email_institucional=null, Email_personal=null, Telefono=null, Movil=null, Direccion=null, Codigo_postal=null, Localidad=null, Provincia=null"));
	  }
  	@Requisitos({"RF11"})
  @Test
  public void pruebaBorrarEncuesta() {
    driver.get("http://localhost:8080/proyecto-war/");
    driver.manage().window().setSize(new Dimension(968, 714));
    driver.get("http://localhost:8080/proyecto-war/indexSecretaria.xhtml");
    driver.findElement(By.linkText("Gestor de encuesta")).click();
    driver.findElement(By.linkText("Borrar una Encuesta")).click();
    driver.findElement(By.id("j_idt6:expediente")).click();
    driver.findElement(By.id("j_idt6:expediente")).sendKeys("123456789");
    driver.findElement(By.id("j_idt6:Fecha")).click();
    driver.findElement(By.id("j_idt6:Fecha")).sendKeys("27-07-2000");
    driver.findElement(By.name("j_idt6:j_idt16")).click();
    driver.findElement(By.linkText("Gestor de encuesta")).click();
    driver.findElement(By.linkText("Leer Encuestas")).click();
    driver.findElement(By.id("j_idt6:expediente")).sendKeys("123456789");
    driver.findElement(By.id("j_idt6:Fecha")).sendKeys("27-07-2000");
    driver.findElement(By.name("j_idt6:j_idt16")).click();
    driver.findElement(By.name("j_idt6:j_idt16")).click();
    driver.findElement(By.cssSelector("tr:nth-child(4) > td:nth-child(2)")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) > td:nth-child(2)")).getText(), is("Encuesta fecha_de_envio=null, grupoPrimero=null, grupoSegundo=null, grupoTercero=null, grupoCuarto=null"));
    driver.findElement(By.linkText("Volver")).click();
  }
  @Requisitos({"RF04"})
  @Test
  public void pruebaLeerAlumno() {
    driver.get("http://localhost:8080/proyecto-war/");
    driver.manage().window().setSize(new Dimension(968, 714));
    driver.get("http://localhost:8080/proyecto-war/indexSecretaria.xhtml");
    driver.findElement(By.linkText("Gestor de alumnos")).click();
    driver.findElement(By.linkText("Leer informacion de un alumno")).click();
    driver.findElement(By.name("j_idt6:j_idt8")).click();
    driver.findElement(By.name("j_idt6:j_idt8")).sendKeys("1");
    driver.findElement(By.name("j_idt6:j_idt10")).click();
    driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(2)")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(2)")).getText(), is("Alumno 1 con DNI=12345678x, Nombre=Pepito, Apellido1=Gonzalez, Apellido2=null, Email_institucional=pepito@uma.es, Email_personal=null, Telefono=null, Movil=null, Direccion=null, Codigo_postal=null, Localidad=null, Provincia=null"));
    driver.findElement(By.linkText("Volver")).click();
    {
      WebElement element = driver.findElement(By.linkText("Volver"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
  }
  	@Requisitos({"RF11"})
  @Test
  public void pruebaLeerEncuesta() {
    driver.get("http://localhost:8080/proyecto-war/");
    driver.manage().window().setSize(new Dimension(968, 714));
    driver.get("http://localhost:8080/proyecto-war/indexSecretaria.xhtml");
    driver.findElement(By.linkText("Gestor de encuesta")).click();
    driver.findElement(By.linkText("Leer Encuestas")).click();
    driver.findElement(By.id("j_idt6:expediente")).click();
    driver.findElement(By.id("j_idt6:expediente")).sendKeys("123456789");
    driver.findElement(By.id("j_idt6:Fecha")).click();
    driver.findElement(By.id("j_idt6:Fecha")).sendKeys("27-07-2000");
    driver.findElement(By.name("j_idt6:j_idt16")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) > td:nth-child(2)")).getText(), is("Encuesta fecha_de_envio=27-07-2000, grupoPrimero=null, grupoSegundo=null, grupoTercero=null, grupoCuarto=4A"));
    driver.findElement(By.linkText("Volver")).click();
  }
  @Requisitos({"RF11"})
  @Test
  public void pruebaCrearEncuesta() {
    driver.get("http://localhost:8080/proyecto-war/");
    driver.manage().window().setSize(new Dimension(1160, 811));
    driver.findElement(By.linkText("Iniciar Sesion")).click();
    driver.findElement(By.id("j_idt6:user")).click();
    driver.findElement(By.id("j_idt6:user")).sendKeys("Pepe");
    driver.findElement(By.id("j_idt6:pass")).sendKeys("pepaso");
    driver.findElement(By.id("j_idt6:pass")).sendKeys(Keys.ENTER);
    driver.findElement(By.id("encuesta:expediente")).click();
    driver.findElement(By.id("encuesta:expediente")).sendKeys("123456789");
    driver.findElement(By.id("encuesta:Fecha")).click();
    driver.findElement(By.id("encuesta:Fecha")).sendKeys("09-06-2021");
    driver.findElement(By.id("encuesta:gp1")).click();
    driver.findElement(By.id("encuesta:gp1")).sendKeys("1A");
    driver.findElement(By.id("encuesta:gp2")).click();
    driver.findElement(By.id("encuesta:gp2")).sendKeys("2B");
    driver.findElement(By.id("encuesta:gp3")).click();
    driver.findElement(By.id("encuesta:gp3")).sendKeys("3A");
    driver.findElement(By.id("encuesta:gp4")).click();
    driver.findElement(By.id("encuesta:gp4")).sendKeys("4A");
    driver.findElement(By.cssSelector("h1")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Encuesta"));
    driver.findElement(By.name("encuesta:j_idt31")).click();
    driver.findElement(By.linkText("Volver al Inicio")).click();
  }
  
}
